name: Update README with Word Count

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # 设置Python版本

    - name: Install dependencies
      run: pip install requests  # 安装requests库

    - name: Update README
      run: |
        python -c "import os; import requests; import json; response = requests.get('https://www.yuque.com/api/books/24381935/overview', cookies={'cookie': os.environ['COOKIE']}); if response.status_code == 200: data = response.json(); readme_content = open('README.md', 'r', encoding='utf-8').read(); updated_content = readme_content.replace('wordCount', str(data['data']['wordCount'])); open('README.md', 'w', encoding='utf-8').write(updated_content);"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update README with new word count"  # 提交更改
        git push  # 推送到GitHub
      env:
        COOKIE: ${{ secrets.YUQUE_COOKIE }}  # 从secrets中获取cookie
